# 设置依赖的镜像
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
# 设置镜像创建者
MAINTAINER hanhongyong
# 设置 ARG
ARG CRON_URL
ARG RC_REMOTE
ARG RC_CONF_URL
# 拷贝scripts
WORKDIR /src
COPY src/. ./
RUN chmod +x *.sh && \
    sed -i "s/CHANGE_CRON_URL/${CRON_URL}/g" entrypoint.sh && \
    sed -i "s/CHANGE_RC_REMOTE/${RC_REMOTE}/g" entrypoint.sh && \
    sed -i "s/CHANGE_RC_CONF_URL/${RC_CONF_URL}/g" entrypoint.sh

# 设置工作目录
WORKDIR /app
# copy 文件到app目录下
COPY Microsoft365_E5_Renew_X/. ./

# 设置环境变量
ENV TZ=Asia/Shanghai

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster

WORKDIR /src
COPY --from=base /src .
WORKDIR /app
COPY --from=base /app .

RUN apt-get update && \
    apt-get install --no-install-recommends -y unzip cron && \
    wget --no-check-certificate -O install-rclone.sh https://rclone.org/install.sh && \
    bash install-rclone.sh && \
    rm -rf install-rclone.sh && \
    dotnet dev-certs https --clean && \
    dotnet dev-certs https

# 预执行命令，容器创建完成后执行的命令，使得程序能够执行
ENTRYPOINT ["/src/entrypoint.sh"]
